exp_name: "shieldgemma-9b"
tracking: true
base_model_name_or_path: "google/shieldgemma-9b"
model_name_or_path: "input/ktr/shieldgemma-9b-bnb-4bit"
base_tokenizer_name_or_path: "google/shieldgemma-9b"
tokenizer_name_or_path: "input/ktr/shieldgemma-9b-bnb-4bit"
learning_rate: 8e-5
train_batch_size: 4
eval_batch_size: 4
eval_steps_ratio: 1.0
save_steps_ratio: 1.0
num_train_epochs: 1
load_in_4bit: True
load_in_8bit: False
gradient_accumulation_steps: 1