[project]
name = "jigsaw"
version = "0.1.0"
description = "shared package"
authors = [
    { name = "ktr", email = "ktr.w1011@gmail.com" }
]
requires-python = "==3.11.*"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"